apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      serviceAccountName: api-aggregator-sa
      containers:
      - name: aggregator
        image: mohamed1780/aggregation:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: aggregator
spec:
  selector:
    app: aggregator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

# kubectl create serviceaccount api-aggregator-sa --namespace default