# permissions for end users to edit demoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custom-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo-editor-role
rules:
- apiGroups:
  - domain.com.mydomain.com
  resources:
  - demoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain.com.mydomain.com
  resources:
  - demoes/status
  verbs:
  - get
