{{- $secret := lookup "v1" "Secret" .Release.Namespace "my-secret-name" -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-name
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}