apiVersion: utopios.net.utopios.net/v1
kind: WebApp
metadata:
  labels:
    app.kubernetes.io/name: tp-operator
    app.kubernetes.io/managed-by: kustomize
  name: webapp-sample
spec:
  # TODO(user): Add fields here
