apiVersion: utopios.net.utopios.net/v1
kind: WebApp
metadata:
  labels:
    app.kubernetes.io/name: tp-operator
    app.kubernetes.io/managed-by: kustomize
  name: webapp-sample-2
spec:
  appName: "nginx-app"
  image: "nginx"
  dbImage: "mysql:5.7"
  replicas: 5
  dbSize: "10Gi"
  autoScaleEnabled: true
  trafficThreshold: 10
