# Utiliser une image de base officielle Python
FROM python:3.8-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de dépendances et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier les fichiers de certificat SSL dans le conteneur
COPY webhook.crt /etc/ssl/certs/webhook_server.crt
COPY webhook.key /etc/ssl/private/webhook_server.key

# Copier le reste du code de l'application dans le répertoire de travail
COPY . .

# Exposer le port sur lequel le serveur Flask va écouter
EXPOSE 443

# Commande pour exécuter l'application
CMD ["python", "main.py"]
