apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      imagePullSecrets:
        - name: registry
      containers:
      - name: webhook-server
        image: webhook-server
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        volumeMounts:
        - name: webhook-certs
          mountPath: "/etc/webhook/certs"
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-server-tls

---

apiVersion: v1
kind: Service
metadata:
  name: conversion-webhook-service
  namespace: default
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: webhook-server



