apiVersion: domain.com.mydomain.com/v1
kind: Demo
metadata:
  labels:
    app.kubernetes.io/name: custom-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo-sample
spec:
  # TODO(user): Add fields here
