 # validating-webhook-configuration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
- name: validating.webhook.admission
  clientConfig:
    service:
      name: admission-validate-controller-webhook-service
      namespace: default
      path: "/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVZEZoZHI1YlVDbFpLNEZHV0ZXUXcrdXFLU1RFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSTBNRFl3T0RFM016a3lORm9ZRHpJdwpOVEV4TURJMU1UY3pPVEkwV2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNXWHBqamVpRkdKTGcxOTk4REZCRkFDbHlvSWNEN2ZuNVoKZGt3TGxlUDY1ck9saHk5VnVVa1BZd0ZVc2lWRW5NbkdRVVdBUnJMKzJCK0FBSVN0UzhjZWtGNUpRek1iaGtZSwpYMU56eDBTUXVPNDJLSXlnZDRKTExFOVdSSEg0bzh5N0N2Qis4T1ZOa3laZkZock4vZGtXUkNsVTRnL1BCck5ICnlvaVlnZ0FRYS9wZEc5Q29SaTIwMHg3VXAyVWJmU25VU2EzdHdSMDFkVTdzTW56YzdKUGJkZm8zb2EyWDVGS3UKVTdFbGZlTk5CV2M4S1F6dFFZa0tLdmw4aTVIZmhSYjZybmo5M1NSTVpRVVZkMlp0ZnBwb2k2RHhhbDBWZ3N4VgpRRUNnWE91OXp2L0NVb2NPMmV0VWc4TTQzMW5LTVp4NkdTUmNxSldMclhJaGFDWmhLem9aQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCUjl4bmkvVks2c21IZmpFWE1QeVVCZ3FlYzgvakFmQmdOVkhTTUVHREFXZ0JSOXhuaS8KVks2c21IZmpFWE1QeVVCZ3FlYzgvakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCejM2ZFhab0xUY3dCeFBHN1Y2K003NFQ3WTk3MXVlTnlOWURxSlVwZjkrRDhqRHh1VEtaVGhUZ2hZCkRDdjNjd0NnUWhJd1NIbmcwWFNlcTk5VnVIZEZFbnZ3MldqWTVxTm52ZFhKcjQzVktDeEZNYjd5WDlpTExJVnAKQ09FbTFrQlVWa0tMOFpEbXA4ZjN6SEsrMks4a2VTeHBsQUtFUEw2WUJBTmlsNE9tN1FMZU5ObUU0WTcwSTBDQQo4Q1NIZzdZZFh4bDhGUnFOQitSOWRVMThNSWJvMDBPb0ZtVUNiQzVFU3BUdnkxZ3NuRUZ0SDZmKzd4cEhDZHkxCmRYaWVJdVZsWnR6a3BMOTYwaEhqL21kam91Z1NIdCtvbmlUM2hhazZwakhNYk16UVozZUpxcXJ1MlFPNjNPMVYKWndUaVgrVmlkMHRnNXV0SFRoYkxqeFYzekoyMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5