apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: democrds.example.com
spec:
  group: example.com
  scope: Cluster
  names:
    kind: DemoCrd
    plural: democrds
    singular: democrd
    shortNames:
      - dc
  versions:
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: integer
                field3:
                  type: integer
    - name: v2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: integer
                field3:
                  type: integer
    - name: v3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: integer
                field4:
                  type: integer
                config:
                  type: object
                  additionalProperties:
                    type: string
  